Refactor the code and add search module
Luka85/FindAdogBreed pull request #15
Opened 2022-11-22 06:43 UTC by Luka85

Vso kodo sem dal v funkcije, tako da se koda ne ponavlja. Dodal sem search module, kjer so vse funkcije povezane z iskanjem na strani. Imam problem, ker mi toggleImage funkcija lepo deluje, ko se stran naloži. Ko pa iščem določeno pasmo, mi vedno ko kliknem prvo pasmo, le-to lepo odpre, če kliknem isto pasmo mi jo zapre, ampak, če pustim prvo odprto in kliknem drugo, mi prve ne zapre. Maš kakšno usmeritev mogoče?

2022-11-22 13:28 UTC, filippotocnik commented
Mogoče nisem bil dost jasen oz se nisva še pogovorila o tem, kako se ponavadi strukturira oz vodi organizacijo znotrej codebase-a. Sej načeloma je vse odvisno od posameznika ampak recimo v tem primeru priznam da sem še bolj zmeden kot sem bil pa prej :) 

kako bi se jaz lotil.. imel bi nek "taglavn" fajl ki se ga polinka v html in to je main file.. v tem se recimo vodi najbolj pomembne funkcionalnosti kot so to da se vse zažene itd.. potem recimo ostale helper, utils funkcije pa imaš najprej razdeljene glede na domeno.

Tvoj main file je script.js, ampak potem pa ti mal naokol pošiljaš variable in funkcije.. neki se exporta, drugo importa itd..

Predlagam da narediš tako da imaš v script.js samo variable in listenerje.. funkcije pa razporediš po fajlih glede na domeno (search posebej, toggleImage posebej recimo). Upam da sem dovolj jasno napisal.. boš vidu pol točno kaj sm hotu povedat.

2022-11-22 14:12 UTC, Luka85 commented
> Mogoče nisem bil dost jasen oz se nisva še pogovorila o tem, kako se ponavadi strukturira oz vodi organizacijo znotrej codebase-a. Sej načeloma je vse odvisno od posameznika ampak recimo v tem primeru priznam da sem še bolj zmeden kot sem bil pa prej :)
> 
> kako bi se jaz lotil.. imel bi nek "taglavn" fajl ki se ga polinka v html in to je main file.. v tem se recimo vodi najbolj pomembne funkcionalnosti kot so to da se vse zažene itd.. potem recimo ostale helper, utils funkcije pa imaš najprej razdeljene glede na domeno.
> 
> Tvoj main file je script.js, ampak potem pa ti mal naokol pošiljaš variable in funkcije.. neki se exporta, drugo importa itd..
> 
> Predlagam da narediš tako da imaš v script.js samo variable in listenerje.. funkcije pa razporediš po fajlih glede na domeno (search posebej, toggleImage posebej recimo). Upam da sem dovolj jasno napisal.. boš vidu pol točno kaj sm hotu povedat.

No zdej si tole precej boljše predstavljam :) A ti imaš potem vedno tako strukturirano kodo? Da se potem tudi v prihodnosti držim tega koncepta. A ti potem že od samega začetka, ko se še planira vse, razdeliš projekt na module? A imaš recimo kak diagram, kjer so vse funckije zabeležene in kjer se lepo vidi, kaj ta določena funcija dela in kako podatki tečejo, itd? Imam težave, ker ko imam recimo par funkcij in se podatki prepletajo, se hitro izgubim.

2022-11-22 14:35 UTC, filippotocnik commented
> > Mogoče nisem bil dost jasen oz se nisva še pogovorila o tem, kako se ponavadi strukturira oz vodi organizacijo znotrej codebase-a. Sej načeloma je vse odvisno od posameznika ampak recimo v tem primeru priznam da sem še bolj zmeden kot sem bil pa prej :)
> > kako bi se jaz lotil.. imel bi nek "taglavn" fajl ki se ga polinka v html in to je main file.. v tem se recimo vodi najbolj pomembne funkcionalnosti kot so to da se vse zažene itd.. potem recimo ostale helper, utils funkcije pa imaš najprej razdeljene glede na domeno.
> > Tvoj main file je script.js, ampak potem pa ti mal naokol pošiljaš variable in funkcije.. neki se exporta, drugo importa itd..
> > Predlagam da narediš tako da imaš v script.js samo variable in listenerje.. funkcije pa razporediš po fajlih glede na domeno (search posebej, toggleImage posebej recimo). Upam da sem dovolj jasno napisal.. boš vidu pol točno kaj sm hotu povedat.
> 
> No zdej si tole precej boljše predstavljam :) A ti imaš potem vedno tako strukturirano kodo? Da se potem tudi v prihodnosti držim tega koncepta. A ti potem že od samega začetka, ko se še planira vse, razdeliš projekt na module? A imaš recimo kak diagram, kjer so vse funckije zabeležene in kjer se lepo vidi, kaj ta določena funcija dela in kako podatki tečejo, itd? Imam težave, ker ko imam recimo par funkcij in se podatki prepletajo, se hitro izgubim.

v tem primeru, bi reku da je nekej narobe s tem funkcijam :D 
če jih dovolj abstrahiraš pol bi mogle delat ne glede na to kaj notr passaš, da ni treba jemati iz local scope-a.

V kasnejši fazi veliko teh strukturnih problemov reši framework.. ampak če se dela vanila JS je pa treba to reševati sam, kdaj tudi z kakšnimi util funkcijami zato da je to lažje, amapk to je že mal bolj advanced :D

2022-11-23 07:38 UTC, filippotocnik commented
> > Mogoče nisem bil dost jasen oz se nisva še pogovorila o tem, kako se ponavadi strukturira oz vodi organizacijo znotrej codebase-a. Sej načeloma je vse odvisno od posameznika ampak recimo v tem primeru priznam da sem še bolj zmeden kot sem bil pa prej :)
> > kako bi se jaz lotil.. imel bi nek "taglavn" fajl ki se ga polinka v html in to je main file.. v tem se recimo vodi najbolj pomembne funkcionalnosti kot so to da se vse zažene itd.. potem recimo ostale helper, utils funkcije pa imaš najprej razdeljene glede na domeno.
> > Tvoj main file je script.js, ampak potem pa ti mal naokol pošiljaš variable in funkcije.. neki se exporta, drugo importa itd..
> > Predlagam da narediš tako da imaš v script.js samo variable in listenerje.. funkcije pa razporediš po fajlih glede na domeno (search posebej, toggleImage posebej recimo). Upam da sem dovolj jasno napisal.. boš vidu pol točno kaj sm hotu povedat.
> 
> A imaš recimo kak diagram, kjer so vse funckije zabeležene in kjer se lepo vidi, kaj ta določena funcija dela in kako podatki tečejo, itd? Imam težave, ker ko imam recimo par funkcij in se podatki prepletajo, se hitro izgubim.

še na tole odgovorim.. nimam nobenih diagramov, imena fileov, imena funkcij morejo bit tok jasna da ni potrebe po nobenih drugih orodjih..

2022-11-29 10:09 UTC, Luka85 commented
Sem dodal še par funkcij in modulov. Ni še dokončano, moram še par funkcij dodati, ampak samo v predogled predno nadaljujem. Zanima me sama struktura, kako se ti zdi? V script.js modulu imam searchBreed funkcijo, ki fetcha podatke glede na search input, in ki jih tudi prikaže na strani, vendar pa sem želel narediti posebej funkcijo, ki fetcha podatke in funkcijo, ki potem te podatke izpiše na strani. Imel sem težave, ker ko returnam podatke is searchBreed funkcije in da bi potem te podatke shranil pod spremenljivko(resultSearchBreed) sem dodal await `const resultSearchBreed= await searchBreed()`, vendar pa mi potem vedno vrze undefined, ker se sama funkcija zažene, ko še nima nobenih search input podatkov. Posledično potem itak ne izpiše nobenih rezultatov seveda. Upam da je razumljivo.

2022-11-29 10:22 UTC, filippotocnik requested changes
Načeloma si se pravilno lotu 👍 

Jaz bi mogoče razmišljal če mal bolj granularno.. recimo vse funkcije, ki fetchajo dato, bi samo fetchale dato in jo returnale v taki strukturi da bi jo potem nasledna funkcija, ki recimo sestavi html s to dato, lahko uporabi. Štekaš?

Ker imaš v parih primerih potrebo po tem da iz date, ki jo dobiš iz APIja, sestaviš html.. tko da lahko pol to abstrahiraš v funkcije. 

Načeloma je cilj to da imaš funkcije, ki delajo samo eno stvar in jih pol lahko med seboj sestavljaš v "večje" funkcije.. to je goal, k tem moreva stremeti v prihodnosti, začniva pa pri prvem koraku 👍

2022-11-29 10:22 UTC, filippotocnik commented on script.js
>  searchInput.focus();
jaz bi tudi to mogoče dal v funkcijo.. samo predlog :D

2022-11-29 10:23 UTC, filippotocnik commented
Spravi zdj do tega da bo vse delalo in lahko zmergaš, pa greva naprej :D

2022-11-29 14:14 UTC, filippotocnik approved these changes
We've got a lot of work to do, but great job.. merge it 🚀

2022-11-29 14:31 UTC, merged