Add input search with the findBreed function
Luka85/FindAdogBreed pull request #2
Opened 2022-11-09 15:11 UTC by Luka85

Dodal sem fukcijo findBreed kjer loopam čez array arrayOfBreeds (tukaj so vsi breedi shranjeni) in če gre čez if statement ( če vsebuje elemente kot searchInput in če searchInput.value NI enak blank space-u), se pravi da ne vsebuje praznega prostora in številke kot prvi znak, potem doda zadetke v <li>, če ne gre skozi vrže <li> s sporočilom "Nothing found. Please try again". Če pride pri fetchanju do napake, vrže isto preko <li> napako, "Not found. Something went wrong. Please try again later"

2022-11-09 18:01 UTC, filippotocnik commented on script.js
>  const searchButton = document.querySelector(".search__button");
Zakaj pa imaš search button, če nič ne dela? 
Mogoče lahko implementiraš da se search zgodi na klik search gumba.. 
hint: poglej malo v api docse, če obstaja prav poseben endpoint za tak primer.

2022-11-09 18:04 UTC, filippotocnik requested changes
sem dodal par komentarjev 👍

2022-11-09 18:04 UTC, filippotocnik commented on script.js
> +    data = resolve.data;
lahko `data` boljše poimenuješ, glede na to da že veš kaj je ta data?

2022-11-10 07:11 UTC, Luka85 commented on script.js
> +    data = resolve.data;
mogoče breedsData?

2022-11-10 07:17 UTC, Luka85 commented on script.js
>  const searchButton = document.querySelector(".search__button");
Bom implemenitral da se search zgodi na klik search gumba
 
Si mislil tole?  https://api.thecatapi.com/v1/breeds/search?q=

2022-11-10 07:25 UTC, filippotocnik commented on script.js
>  const searchButton = document.querySelector(".search__button");
ja 👍

2022-11-10 11:15 UTC, Luka85 commented
Sedaj sem popravil par stvari, in sicer sem popravil da je gumb Search vezan na findBreed function, kjer fetcham podatke iz api glede na search input( search endpoint), odstranil sem array, ker sem prej imel le-tega samo za preverjanje če ustreza input value kriterijem (npr. da uporabnik ne uporabi blank space kot prvi character). Deluje na podoben princip, če ni zadetkov, uporabniku prikaže obvestilo, da ničesar ni bilo najdeno.

2022-11-10 12:07 UTC, filippotocnik commented
> Sedaj sem popravil par stvari, in sicer sem popravil da je gumb Search vezan na findBreed function, kjer fetcham podatke iz api glede na search input( search endpoint), odstranil sem array, ker sem prej imel le-tega samo za preverjanje če ustreza input value kriterijem (npr. da uporabnik ne uporabi blank space kot prvi character). Deluje na podoben princip, če ni zadetkov, uporabniku prikaže obvestilo, da ničesar ni bilo najdeno.

sem ti na slacku odgovoru, lahko glede na to narediš še kakšen improvement.. drugače je pa uredu 👍 lahko tudi kasneje še spimpaš

2022-11-10 14:07 UTC, merged